<a href="https://colab.research.google.com/github/Jcain17/Intro_to_ML/blob/main/ML_HW5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [417]:
%matplotlib inline
import torch
import numpy as np
import torch.optim as optim
torch.set_printoptions(edgeitems=2)

In [418]:
# make dataset
tc = [0.5,14.0,15.0,28.0,11.0,8.0,3.0,-4.0,6.0,13.0,21.0]
tu = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
# make tensors
tc = torch.tensor(tc)
tu = torch.tensor(tu)
tun = 0.01 * tu

In [419]:
def nonlin(tu, w1, w2, b):
  return w2*tu**2 + w1*tu + b

def lin(tu, w, b):
  return w * tu + b

In [420]:
w1 = torch.ones(())
w2 = torch.ones(())
b = torch.ones(())
w = torch.ones(())

tp = nonlin(tu, w1, w2, b)
tp

tensor([1311.1901, 3181.7100, 3446.4399, 6790.5103, 3226.9900, 2441.1101,
        1184.1101,  498.0399, 2391.9600, 3709.5601, 4747.9600])

In [421]:
tp = lin(tu, w, b)
tp

tensor([36.7000, 56.9000, 59.2000, 82.9000, 57.3000, 49.9000, 34.9000, 22.8000,
        49.4000, 61.4000, 69.4000])

In [422]:
def loss_fun(tp, tc):
  diff = (tp - tc)**2
  return diff.mean()

In [423]:
params = torch.tensor([1.0, 0.0, 0.0], requires_grad=True)

learning_rate = 0.00001
nonlinopt = optim.SGD([params], lr= learning_rate)

In [424]:
nonlintp = nonlin(tu, *params)

nonlinloss = loss_fun(nonlintp, tc)
nonlinloss.backward()

nonlinopt.step()

params

tensor([ 9.5483e-01, -2.6670e+00, -8.2600e-04], requires_grad=True)

In [425]:
lin_param = torch.tensor([1.0, 0.0], requires_grad=True)

linopt = optim.SGD([lin_param], lr = learning_rate)

In [426]:
lintp = lin(tu, *lin_param)

linloss = loss_fun(lintp, tc)
linloss.backward()

linopt.step()

lin_param

tensor([ 9.5483e-01, -8.2600e-04], requires_grad=True)

In [427]:
def train_loop(n_epochs, optimizer, params, tu, tc):
  for epoch in range(1, n_epochs + 1):
    tp = nonlin(tu, *params)
    loss = loss_fun(tp, tc)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 500 == 0:
      print('Epoch %d, Loss %f' % (epoch, float(loss)))

  return params

In [428]:
def lintrain_loop(n_epochs, optimizer, lin_param, tu, tc):
  for epoch in range(1, n_epochs + 1):
    tp = lin(tu, *lin_param)
    loss = loss_fun(tp, tc)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 500 == 0:
      print('Epoch %d, Loss %f' % (epoch, float(loss)))

  return lin_param

In [429]:
#Training A: learning rate = 0.1
n_epoch = 5000
learn_rate = 0.1
optimizer = optim.SGD([params], lr = learn_rate)

train_loop(n_epoch, optimizer, params, tun, tc)

Epoch 500, Loss 2.113502
Epoch 1000, Loss 2.093012
Epoch 1500, Loss 2.092790
Epoch 2000, Loss 2.092597
Epoch 2500, Loss 2.092420
Epoch 3000, Loss 2.092261
Epoch 3500, Loss 2.092117
Epoch 4000, Loss 2.091986
Epoch 4500, Loss 2.091866
Epoch 5000, Loss 2.091761


tensor([ 25.7966,  27.3118, -10.8946], requires_grad=True)

In [430]:
#Training B: learning rate = 0.01
n_epoch = 5000
learn_rate = 0.01
optimizer = optim.SGD([params], lr = learn_rate)

train_loop(n_epoch, optimizer, params, tun, tc)

Epoch 500, Loss 2.091751
Epoch 1000, Loss 2.091741
Epoch 1500, Loss 2.091730
Epoch 2000, Loss 2.091721
Epoch 2500, Loss 2.091711
Epoch 3000, Loss 2.091702
Epoch 3500, Loss 2.091692
Epoch 4000, Loss 2.091684
Epoch 4500, Loss 2.091674
Epoch 5000, Loss 2.091665


tensor([ 25.7485,  27.3592, -10.8836], requires_grad=True)

In [431]:
#Training C: learning rate = 0.001
n_epoch = 5000
learn_rate = 0.001
optimizer = optim.SGD([params], lr = learn_rate)

train_loop(n_epoch, optimizer, params, tun, tc)

Epoch 500, Loss 2.091664
Epoch 1000, Loss 2.091664
Epoch 1500, Loss 2.091664
Epoch 2000, Loss 2.091664
Epoch 2500, Loss 2.091664
Epoch 3000, Loss 2.091664
Epoch 3500, Loss 2.091664
Epoch 4000, Loss 2.091664
Epoch 4500, Loss 2.091664
Epoch 5000, Loss 2.091664


tensor([ 25.7484,  27.3592, -10.8836], requires_grad=True)

In [432]:
#Training D: learning rate = 0.0001
n_epoch = 5000
learn_rate = 0.0001
optimizer = optim.SGD([params], lr = learn_rate)

train_loop(n_epoch, optimizer, params, tun, tc)

Epoch 500, Loss 2.091664
Epoch 1000, Loss 2.091664
Epoch 1500, Loss 2.091664
Epoch 2000, Loss 2.091664
Epoch 2500, Loss 2.091664
Epoch 3000, Loss 2.091664
Epoch 3500, Loss 2.091664
Epoch 4000, Loss 2.091664
Epoch 4500, Loss 2.091664
Epoch 5000, Loss 2.091664


tensor([ 25.7484,  27.3592, -10.8836], requires_grad=True)

In [433]:
# Linear Training A: learning rate = 0.1
n_epoch = 5000
learn_rate = 0.1
optimizer = optim.SGD([lin_param], lr = learn_rate)

lintrain_loop(n_epoch, optimizer, lin_param, tun, tc)

Epoch 500, Loss 3.988030
Epoch 1000, Loss 2.946082
Epoch 1500, Loss 2.927962
Epoch 2000, Loss 2.927649
Epoch 2500, Loss 2.927644
Epoch 3000, Loss 2.927644
Epoch 3500, Loss 2.927644
Epoch 4000, Loss 2.927644
Epoch 4500, Loss 2.927644
Epoch 5000, Loss 2.927644


tensor([ 53.6767, -17.3045], requires_grad=True)

In [434]:
# Linear Training B: learning rate = 0.01
n_epoch = 5000
learn_rate = 0.01
optimizer = optim.SGD([lin_param], lr = learn_rate)

lintrain_loop(n_epoch, optimizer, lin_param, tun, tc)

Epoch 500, Loss 2.927644
Epoch 1000, Loss 2.927644
Epoch 1500, Loss 2.927644
Epoch 2000, Loss 2.927644
Epoch 2500, Loss 2.927644
Epoch 3000, Loss 2.927644
Epoch 3500, Loss 2.927644
Epoch 4000, Loss 2.927644
Epoch 4500, Loss 2.927644
Epoch 5000, Loss 2.927644


tensor([ 53.6767, -17.3045], requires_grad=True)

In [435]:
# Linear Training C: learning rate = 0.001
n_epoch = 5000
learn_rate = 0.001
optimizer = optim.SGD([lin_param], lr = learn_rate)

lintrain_loop(n_epoch, optimizer, lin_param, tun, tc)

Epoch 500, Loss 2.927644
Epoch 1000, Loss 2.927644
Epoch 1500, Loss 2.927644
Epoch 2000, Loss 2.927644
Epoch 2500, Loss 2.927644
Epoch 3000, Loss 2.927644
Epoch 3500, Loss 2.927644
Epoch 4000, Loss 2.927644
Epoch 4500, Loss 2.927644
Epoch 5000, Loss 2.927644


tensor([ 53.6767, -17.3045], requires_grad=True)

In [436]:
# Linear Training D: learning rate = 0.0001
n_epoch = 5000
learn_rate = 0.0001
optimizer = optim.SGD([lin_param], lr = learn_rate)

lintrain_loop(n_epoch, optimizer, lin_param, tun, tc)

Epoch 500, Loss 2.927644
Epoch 1000, Loss 2.927644
Epoch 1500, Loss 2.927644
Epoch 2000, Loss 2.927644
Epoch 2500, Loss 2.927644
Epoch 3000, Loss 2.927644
Epoch 3500, Loss 2.927644
Epoch 4000, Loss 2.927644
Epoch 4500, Loss 2.927644
Epoch 5000, Loss 2.927644


tensor([ 53.6767, -17.3045], requires_grad=True)

In [437]:
# ADAM Training Non-Linear A: learning rate = 0.1

n_epochs = 5000
learn_rate = 0.1
optimizer = optim.Adam([params], lr = learn_rate)

train_loop(n_epoch, optimizer, params, tun, tc)

Epoch 500, Loss 2.090718
Epoch 1000, Loss 2.090719
Epoch 1500, Loss 2.090719
Epoch 2000, Loss 2.090998
Epoch 2500, Loss 2.090719
Epoch 3000, Loss 2.090718
Epoch 3500, Loss 2.090719
Epoch 4000, Loss 2.090718
Epoch 4500, Loss 2.090717
Epoch 5000, Loss 2.090765


tensor([ 24.7657,  28.3096, -10.6443], requires_grad=True)

In [438]:
# ADAM Training Non-Linear B: learning rate = 0.01

n_epochs = 5000
learn_rate = 0.01
optimizer = optim.Adam([params], lr = learn_rate)

train_loop(n_epoch, optimizer, params, tun, tc)

Epoch 500, Loss 2.090719
Epoch 1000, Loss 2.090718
Epoch 1500, Loss 2.090718
Epoch 2000, Loss 2.090717
Epoch 2500, Loss 2.090717
Epoch 3000, Loss 2.090718
Epoch 3500, Loss 2.090719
Epoch 4000, Loss 2.090718
Epoch 4500, Loss 2.090718
Epoch 5000, Loss 2.090718


tensor([ 24.7604,  28.3043, -10.6496], requires_grad=True)

In [439]:
# ADAM Training Non-Linear C: learning rate = 0.001

n_epochs = 5000
learn_rate = 0.001
optimizer = optim.Adam([params], lr = learn_rate)

train_loop(n_epoch, optimizer, params, tun, tc)

Epoch 500, Loss 2.090718
Epoch 1000, Loss 2.090719
Epoch 1500, Loss 2.090717
Epoch 2000, Loss 2.090718
Epoch 2500, Loss 2.090718
Epoch 3000, Loss 2.090718
Epoch 3500, Loss 2.090718
Epoch 4000, Loss 2.090718
Epoch 4500, Loss 2.090718
Epoch 5000, Loss 2.090718


tensor([ 24.7604,  28.3043, -10.6496], requires_grad=True)

In [440]:
# ADAM Training Non-Linear D: learning rate = 0.0001

n_epochs = 5000
learn_rate = 0.0001
optimizer = optim.Adam([params], lr = learn_rate)

train_loop(n_epoch, optimizer, params, tun, tc)

Epoch 500, Loss 2.090718
Epoch 1000, Loss 2.090718
Epoch 1500, Loss 2.090719
Epoch 2000, Loss 2.090717
Epoch 2500, Loss 2.090718
Epoch 3000, Loss 2.090717
Epoch 3500, Loss 2.090719
Epoch 4000, Loss 2.090717
Epoch 4500, Loss 2.090719
Epoch 5000, Loss 2.090719


tensor([ 24.7604,  28.3043, -10.6496], requires_grad=True)

In [441]:
# ADAM Training Linear A: learning rate = 0.1

n_epochs = 5000
learn_rate = 0.1
optimizer = optim.Adam([lin_param], lr = learn_rate)

lintrain_loop(n_epoch, optimizer, lin_param, tun, tc)

Epoch 500, Loss 2.927643
Epoch 1000, Loss 2.927644
Epoch 1500, Loss 2.927664
Epoch 2000, Loss 2.927643
Epoch 2500, Loss 2.927642
Epoch 3000, Loss 2.927644
Epoch 3500, Loss 2.927642
Epoch 4000, Loss 2.927644
Epoch 4500, Loss 2.927644
Epoch 5000, Loss 2.927644


tensor([ 53.6773, -17.3047], requires_grad=True)

In [442]:
# ADAM Training Linear B: learning rate = 0.01

n_epochs = 5000
learn_rate = 0.01
optimizer = optim.Adam([lin_param], lr = learn_rate)

lintrain_loop(n_epoch, optimizer, lin_param, tun, tc)

Epoch 500, Loss 2.927643
Epoch 1000, Loss 2.927643
Epoch 1500, Loss 2.927643
Epoch 2000, Loss 2.927644
Epoch 2500, Loss 2.927642
Epoch 3000, Loss 2.927644
Epoch 3500, Loss 2.927643
Epoch 4000, Loss 2.927644
Epoch 4500, Loss 2.927643
Epoch 5000, Loss 2.927646


tensor([ 53.6764, -17.3056], requires_grad=True)

In [443]:
# ADAM Training Linear C: learning rate = 0.001

n_epochs = 5000
learn_rate = 0.001
optimizer = optim.Adam([lin_param], lr = learn_rate)

lintrain_loop(n_epoch, optimizer, lin_param, tun, tc)

Epoch 500, Loss 2.927643
Epoch 1000, Loss 2.927643
Epoch 1500, Loss 2.927642
Epoch 2000, Loss 2.927643
Epoch 2500, Loss 2.927642
Epoch 3000, Loss 2.927644
Epoch 3500, Loss 2.927643
Epoch 4000, Loss 2.927643
Epoch 4500, Loss 2.927644
Epoch 5000, Loss 2.927643


tensor([ 53.6772, -17.3048], requires_grad=True)

In [444]:
# ADAM Training Linear D: learning rate = 0.0001

n_epochs = 5000
learn_rate = 0.0001
optimizer = optim.Adam([lin_param], lr = learn_rate)

lintrain_loop(n_epoch, optimizer, lin_param, tun, tc)

Epoch 500, Loss 2.927643
Epoch 1000, Loss 2.927643
Epoch 1500, Loss 2.927643
Epoch 2000, Loss 2.927643
Epoch 2500, Loss 2.927643
Epoch 3000, Loss 2.927643
Epoch 3500, Loss 2.927643
Epoch 4000, Loss 2.927643
Epoch 4500, Loss 2.927643
Epoch 5000, Loss 2.927643


tensor([ 53.6772, -17.3048], requires_grad=True)