<a href="https://colab.research.google.com/github/Jcain17/Intro_to_ML/blob/main/ML_HW5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [200]:
%matplotlib inline
import torch
import numpy as np
import torch.optim as optim
from google.colab import drive
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [201]:
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/Housing.csv'
housing = pd.DataFrame(pd.read_csv(file_path))
housing.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [202]:
sc_X = StandardScaler()
varlist1 = ['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking']
housing[varlist1] = sc_X.fit_transform(housing[varlist1])

In [203]:
varlist = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking']

X = housing[varlist].values
Y = housing['price']

In [204]:
X

array([[ 1.04672629,  1.40341936,  1.42181174,  1.37821692,  1.51769249],
       [ 1.75700953,  1.40341936,  5.40580863,  2.53202371,  2.67940935],
       [ 2.21823241,  0.04727831,  1.42181174,  0.22441013,  1.51769249],
       ...,
       [-0.70592066, -1.30886273, -0.57018671, -0.92939666, -0.80574124],
       [-1.03338891,  0.04727831, -0.57018671, -0.92939666, -0.80574124],
       [-0.5998394 ,  0.04727831, -0.57018671,  0.22441013, -0.80574124]])

In [205]:
Y

0      4.566365
1      4.004484
2      4.004484
3      3.985755
4      3.554979
         ...   
540   -1.576868
541   -1.605149
542   -1.614327
543   -1.614327
544   -1.614327
Name: price, Length: 545, dtype: float64

In [206]:
x = torch.tensor(X)
y = torch.tensor(Y)
x,y

(tensor([[ 1.0467,  1.4034,  1.4218,  1.3782,  1.5177],
         [ 1.7570,  1.4034,  5.4058,  2.5320,  2.6794],
         [ 2.2182,  0.0473,  1.4218,  0.2244,  1.5177],
         ...,
         [-0.7059, -1.3089, -0.5702, -0.9294, -0.8057],
         [-1.0334,  0.0473, -0.5702, -0.9294, -0.8057],
         [-0.5998,  0.0473, -0.5702,  0.2244, -0.8057]], dtype=torch.float64),
 tensor([ 4.5664e+00,  4.0045e+00,  4.0045e+00,  3.9858e+00,  3.5550e+00,
          3.2553e+00,  2.8807e+00,  2.8807e+00,  2.7309e+00,  2.6934e+00,
          2.6934e+00,  2.6297e+00,  2.4312e+00,  2.3938e+00,  2.3938e+00,
          2.3188e+00,  2.3188e+00,  2.2439e+00,  2.2065e+00,  2.1877e+00,
          2.1315e+00,  2.0941e+00,  2.0754e+00,  2.0754e+00,  2.0379e+00,
          2.0192e+00,  1.9780e+00,  1.9443e+00,  1.9443e+00,  1.9443e+00,
          1.9443e+00,  1.9443e+00,  1.8881e+00,  1.8319e+00,  1.7944e+00,
          1.7735e+00,  1.7532e+00,  1.7195e+00,  1.7101e+00,  1.6820e+00,
          1.6633e+00,  1.6446e+00, 

In [207]:
#Data split
n_samples = x.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices

(tensor([270, 444, 407, 273, 425,  62, 312,  71, 176, 163, 435, 384, 286,  84,
         369,  44, 482, 373, 336, 416, 323,  18, 154, 293, 276,  48, 207, 173,
         512, 133, 410,  54, 144, 383, 277,  20,  52, 453, 221, 131, 295,  10,
         353, 466, 198, 319, 112, 287, 311, 487, 497, 240, 518, 461,  69, 432,
          40, 148, 121, 228, 291, 107,  11, 469, 354, 524,  89, 205, 450, 215,
         235, 494, 199, 257,   7,  47, 329, 115, 359,  93, 344, 377, 296, 137,
         116, 480,  13, 149, 280, 332, 514,  81, 531, 124, 473, 379, 434, 261,
          66,  34, 203, 417, 108, 328, 165,  23, 443, 508, 431, 462,  28, 382,
         222, 143, 192,   6, 197, 324,  32,  39, 308, 135,  45, 499, 411, 288,
          73, 476, 368, 298, 347, 477, 386, 393,  79, 275, 120,  67,  96, 279,
          88, 341,  46, 315, 526, 426, 371, 254, 491, 424, 250, 437, 455, 313,
         433, 316, 200,  37, 515, 255,  31, 159, 301, 126, 106, 517, 470, 321,
         262, 365, 422,  74, 238, 169, 152, 314, 535

In [208]:
train_x = x[train_indices]

val_x = x[val_indices]

train_xu = x[train_indices]

val_xu = x[val_indices]

train_y = y[train_indices]

val_y = y[val_indices]

In [209]:
def lin(x, w0, w1, w2, w3, w4, w5):
  return w0 + x[:,0]*w1 + x[:,1]*w2 + x[:,2]*w3 + x[:,3]*w4 + x[:,4]*w5

In [210]:
def loss_fun(tp, tc):
  diff = (tp - tc)**2
  return diff.mean()

In [211]:
w0 = torch.ones(())
w1 = torch.ones(())
w2 = torch.ones(())
w3 = torch.ones(())
w4 = torch.ones(())
w5 = torch.ones(())

tp = lin(train_x, w0, w1, w2, w3, w4, w5)
tp

tensor([ 3.9032e+00, -1.0408e+00, -3.3666e-01,  2.8141e+00, -1.1973e+00,
         4.9081e+00, -1.9732e+00,  5.9433e+00,  2.6195e+00, -4.8575e-01,
        -3.1264e+00, -2.9142e+00, -2.3482e+00,  1.5778e+00, -3.3293e+00,
         7.1050e+00, -1.0269e+00, -2.4523e+00,  2.4165e+00,  2.8106e-01,
         2.3422e+00,  3.9573e+00,  3.5191e+00, -1.7940e+00, -1.7986e+00,
         2.6572e+00, -1.0961e+00,  2.1590e+00, -2.4523e+00,  8.8789e-01,
        -1.8579e+00,  3.4413e+00,  2.2058e+00,  5.2673e+00,  9.5025e-01,
         1.8361e+00,  7.1050e+00, -2.4125e+00,  2.4457e+00,  3.8720e+00,
        -1.4074e+00,  5.9318e+00, -8.7277e-03, -1.0546e+00,  2.6357e-01,
         3.7373e+00,  5.5639e+00,  5.6939e-02, -1.0330e+00,  1.3670e+00,
        -3.1753e+00,  4.5303e-01, -3.3755e+00, -2.7021e+00,  8.7680e+00,
        -8.3858e-01,  5.4122e-01,  1.6074e+00,  8.5532e-01,  1.5179e+00,
        -1.1178e+00,  1.6351e+00,  7.9511e+00, -2.8681e+00,  4.6254e-02,
        -3.4843e+00,  1.0497e+01,  1.5955e+00, -8.8

In [212]:
def training_loop(n_epochs, optimizer, params, train_t_u, val_t_u,
                  train_t_c, val_t_c):
    for epoch in range(1, n_epochs + 1):
        train_t_p = lin(train_t_u, *params)
        train_loss = loss_fun(train_t_p, train_t_c)

        val_t_p = lin(val_t_u, *params)
        val_loss = loss_fun(val_t_p, val_t_c)

        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        if epoch <= 3 or epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"
                  f" Validation loss {val_loss.item():.4f}")

    return params

In [213]:
params = torch.tensor([1.0, 0.0, 0.0, 0.0, 0.0, 0.0], requires_grad=True)
learning_rate = 0.001
optimizer = optim.SGD([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_t_u = train_xu,
    val_t_u = val_xu,
    train_t_c = train_y,
    val_t_c = val_y)

Epoch 1, Training loss 1.9403, Validation loss 2.2388
Epoch 2, Training loss 1.9324, Validation loss 2.2306
Epoch 3, Training loss 1.9245, Validation loss 2.2225
Epoch 500, Training loss 0.5808, Validation loss 0.7389
Epoch 1000, Training loss 0.4505, Validation loss 0.5429
Epoch 1500, Training loss 0.4330, Validation loss 0.5002
Epoch 2000, Training loss 0.4303, Validation loss 0.4878
Epoch 2500, Training loss 0.4299, Validation loss 0.4836
Epoch 3000, Training loss 0.4298, Validation loss 0.4821
Epoch 3500, Training loss 0.4297, Validation loss 0.4815
Epoch 4000, Training loss 0.4297, Validation loss 0.4812
Epoch 4500, Training loss 0.4297, Validation loss 0.4811
Epoch 5000, Training loss 0.4297, Validation loss 0.4811


tensor([0.0278, 0.3661, 0.0669, 0.3252, 0.2378, 0.1885], requires_grad=True)

In [214]:
params = torch.tensor([1.0, 0.0, 0.0, 0.0, 0.0, 0.0], requires_grad=True)
learning_rate = 0.001
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_t_u = train_xu,
    val_t_u = val_xu,
    train_t_c = train_y,
    val_t_c = val_y)

Epoch 1, Training loss 1.9403, Validation loss 2.2388
Epoch 2, Training loss 1.9338, Validation loss 2.2325
Epoch 3, Training loss 1.9274, Validation loss 2.2261
Epoch 500, Training loss 0.7238, Validation loss 0.9329
Epoch 1000, Training loss 0.4866, Validation loss 0.6058
Epoch 1500, Training loss 0.4358, Validation loss 0.5090
Epoch 2000, Training loss 0.4300, Validation loss 0.4861
Epoch 2500, Training loss 0.4297, Validation loss 0.4817
Epoch 3000, Training loss 0.4297, Validation loss 0.4811
Epoch 3500, Training loss 0.4297, Validation loss 0.4811
Epoch 4000, Training loss 0.4297, Validation loss 0.4811
Epoch 4500, Training loss 0.4297, Validation loss 0.4811
Epoch 5000, Training loss 0.4297, Validation loss 0.4811


tensor([0.0278, 0.3663, 0.0664, 0.3255, 0.2381, 0.1884], requires_grad=True)